name: Rust - build&test on Win

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test:
    name: Build & run Win tests
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose -- --nocapture test_win

  create_release:
    name: Create release
    runs-on: windows-latest
    # Note this. We are going to use that in further jobs.
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Delete old release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          delete_release: true
          tag_name: release_win
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release_win
          release_name: Release for Win
          draft: false
          prerelease: false

  release_assets:
    name: Release assets
    needs: [build_test, create_release] # we need to know the upload URL
    runs-on: windows-latest
    steps:
      # checkout of cource
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build release
        run:  cargo build --release
      - name: Copy batch file
        run:  copy .\assets\dnddice.bat .\target\release
      - name: Zip release
        run:  tar.exe -C .\target\release -acf dnddice-win.zip dnddice.exe dnddice.bat
      - name: Delete batch file
        run:  del .\target\release\dnddice.bat
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          # This is how it will be named on the release page. Put hatever name
          # you like, remember that they need to be different for each platform.
          # You can choose any build matrix parameters. For Rust I use the
          # target triple.
          asset_name: dnddice-win.zip
          # The path to the file you want to upload.
          asset_path: .\dnddice-win.zip
          # probably you will need to change it, but most likely you are
          # uploading a binary file
          asset_content_type: application/zip         
