name: Rust - build&test on Win

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    #- name: Run tests
    #  run: cargo test --verbose -- --nocapture test_win

  test:
    name: Run Win tests
    needs: build
    runs-on: windows-latest
    steps:
      # checkout of cource
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run:  cargo test --verbose -- --nocapture test_win

  create_release:
    name: Create release
    runs-on: ubuntu-latest
    # Note this. We are going to use that in further jobs.
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release
          release_name: Release for Win
          draft: false
          prerelease: false

  release_assets:
    name: Release assets
    needs: [build, test, create_release] # we need to know the upload URL
    runs-on: windows-latest
    steps:
      # checkout of cource
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build release
        run:  cargo build --release
      - name: Zip release
        run:  tar.exe -a -c -f dnddice-win.zip .\target\release\dnddice.exe
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          # This is how it will be named on the release page. Put hatever name
          # you like, remember that they need to be different for each platform.
          # You can choose any build matrix parameters. For Rust I use the
          # target triple.
          asset_name: dnddice-win.zip
          # The path to the file you want to upload.
          asset_path: .\dnddice-win.zip
          # probably you will need to change it, but most likely you are
          # uploading a binary file
          asset_content_type: application/zip         
